### PR TITLE
Netcat for python3

### PR DESCRIPTION
**Pull request by Dundee**
Fastrpc-netcat working in Python 3

### CODE REVIEW

**Comment by volca02** [comment]
Could this be merged into a single commit change? it's pretty much impossible to see what exactly changed

**Comment by Dundee** [comment]
Pushed as https://github.com/Dundee/fastrpc/commit/dc2dff192f4999aaa62732c2d1007b01c1cef90d .

Does it seem better for you?

**Comment by volca02** [comment]
yes, that's what was missing. Can you re-issue a pull req. with that?

**Comment by Dundee** [comment]
Sure.

**Pull request closed without merging**
